annotations:
  data_folder_path: C:\Users\anaja\OneDrive\Documents\Ecole\TUHH\Semester 3\Projektarbeit\Data\CURAC
  traj_name: traj_random6
  log_name: trajrandom6.txt
images:
  img_root: C:\Users\anaja\OneDrive\Documents\Ecole\TUHH\Semester 3\Projektarbeit\Dataset_sample\CURAC
merge_trajectories:
  traj_to_merge:
    - traj_random_slbo.csv
    - traj_random_slt.csv
    - traj_random_srbo.csv
    - traj_random_srt.csv
  merged_file_name: traj_merged_red_rot
  filter_rot: True
  filter_oof: True
  test_ratio: 0.2
  valid_ratio: 0.25
add_real_bgnd:
  bgnd_img_paths:
    - chair_background.jpg
  trajectory_annotations:
    - traj_random0_mini.csv
    # - traj_random3_mini.csv
    # - traj_random4_mini.csv