annotations:
  data_folder_path: /data/Boudreault/mandible_videos
  traj_name: traj_slice_y90_sec0_occ
  log_name: trajslicey90sec0occ.txt
images:
  img_root: /data/Boudreault/mandible_data
merge_trajectories:
  traj_to_merge:
    # - traj_slice_y10_sec0.csv
    # - traj_slice_y10_sec1.csv
    # - traj_slice_y10_sec2.csv
    - traj_slice_y20_sec0_occ.csv
    - traj_slice_y20_sec1_occ.csv
    - traj_slice_y20_sec2_occ.csv
    - traj_slice_y30_sec0_occ.csv
    - traj_slice_y30_sec1_occ.csv
    - traj_slice_y30_sec2_occ.csv
    - traj_slice_y40_sec0_occ.csv
    - traj_slice_y40_sec1_occ.csv
    - traj_slice_y40_sec2_occ.csv
    - traj_slice_y50_sec0_occ.csv
    - traj_slice_y50_sec1_occ.csv
    - traj_slice_y50_sec2_occ.csv
    - traj_slice_y60_sec0_occ.csv
    - traj_slice_y60_sec1_occ.csv
    - traj_slice_y60_sec2_occ.csv
    - traj_slice_y70_sec0_occ.csv
    - traj_slice_y70_sec1_occ.csv
    - traj_slice_y70_sec2_occ.csv
    - traj_slice_y80_sec0_occ.csv
    - traj_slice_y80_sec1_occ.csv
    - traj_slice_y80_sec2_occ.csv
    - traj_slice_y90_sec0_occ.csv
    - traj_slice_y90_sec1_occ.csv
    - traj_slice_y90_sec2_occ.csv
  merged_file_name: traj_slice_y_occ
  filter_rot: True
  filter_oof: True
  test_ratio: 0.2
  valid_ratio: 0.25
add_real_bgnd:
  bgnd_img_paths:
    - chair_background.jpg
  trajectory_annotations:
    - traj_slice_y_no_oof_train.csv
    - traj_slice_z_no_oof_train.csv
    - traj_slice_y_occ_train.csv
    - traj_slice_y_no_oof_valid.csv
    - traj_slice_z_no_oof_valid.csv
    - traj_slice_y_occ_valid.csv
    # - traj_slice_y_no_oof_test.csv
    # - traj_slice_z_no_oof_test.csv
    # - traj_slice_y_occ_test.csv